### PR TITLE
Feature/22-user-actions

### PR DESCRIPTION
**Pull request by lifenautjoe**
# Demo

user-profile-actions

### CODE REVIEW

**Comment by lifenautjoe** [comment]
@Komposten The messages about missing buttons was an outdated branch. I've pulled the latest and its there.

The blocking issue will address on another branch.

**Comment by Komposten** [comment]
@lifenautjoe Interesting. I just pulled the branch down and ran it. How does that pull an outdated version? 🤔

**Comment by lifenautjoe** [comment]
Yeah its weird. Try searching for "Updaet" on the repository. I couldnt find it anymore.

**Comment by Komposten** [comment]
Hmm, just checked my local git log and it looks like it only pulled up to c675cb2 ("✨ display User actions").

**Pull request merged**
